/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UContainer: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UTooltip: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UApp: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UBadge: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UContainer: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  const UTooltip: typeof import('./../../../node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@0b06c38_@nuxt+content@3.12.0_better-sqlite3@12.6.2_eef50da3b98b5bc8574e7d8f825593a2/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
}