<script setup lang="ts">
import { Comark } from '@comark/vue'
import footnotes from '@comark/vue/plugins/footnotes'

const markdown = `
# Footnotes Plugin Example

Comark supports footnotes via the \`footnotes\` plugin. Footnote references use \`[^label]\` syntax inline, and definitions use \`[^label]: content\` at the bottom of your document.

## Basic Usage

The theory of relativity[^1] revolutionized modern physics. It was built on earlier work by Lorentz and Poincaré[^2].

Quantum mechanics[^3] describes nature at the smallest scales of energy levels of atoms and subatomic particles.

## Footnotes in Rich Text

Markdown formatting works alongside footnotes — for example **bold text with a reference[^4]** or *italicized context[^5]*.

## Multiple References

A single footnote can provide important context[^1] and can be referenced more than once throughout the document.

---

*The footnotes section below is auto-generated by the plugin.*

[^1]: Albert Einstein published the theory of special relativity in 1905 and general relativity in 1915.
[^2]: Hendrik Lorentz and Henri Poincaré contributed foundational work on electrodynamics.
[^3]: Quantum mechanics was developed in the early 20th century by Planck, Bohr, Heisenberg, Schrödinger, and others.
[^4]: Bold formatting is preserved — the footnote reference appears inline within the bold text.
[^5]: Italic text works the same way with embedded footnote references.
`
</script>

<template>
  <Suspense>
    <Comark :plugins="[footnotes()]">
      {{ markdown }}
    </Comark>
  </Suspense>
</template>

<style>
body {
  font-family: system-ui, -apple-system, sans-serif;
  max-width: 720px;
  margin: 2rem auto;
  padding: 0 1rem;
  line-height: 1.6;
  color: #1a1a1a;
}

.footnote-ref {
  font-size: 0.75em;
  vertical-align: super;
  line-height: 0;
}

.footnote-ref a {
  color: #2563eb;
  text-decoration: none;
}

.footnote-ref a:hover {
  text-decoration: underline;
}

.footnotes {
  margin-top: 2rem;
  font-size: 0.9em;
  color: #555;
}

.footnotes hr {
  border: none;
  border-top: 1px solid #ddd;
  margin-bottom: 1rem;
}

.footnotes h2 {
  font-size: 1.1em;
  margin-bottom: 0.5rem;
}

.footnotes-list {
  padding-left: 1.5em;
}

.footnotes-list li {
  margin-bottom: 0.4em;
}

.footnote-backref {
  color: #2563eb;
  text-decoration: none;
  margin-left: 0.25em;
}

.footnote-backref:hover {
  text-decoration: underline;
}
</style>
